TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 1000
  per_device_train_batch_size: 1
  weights_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 1000
  save_steps: 1000000
  gradient_accumulation_steps: 128
